### ISSUE TITLE
Changing fuel types doesn't refresh list

### ISSUE THREAD

**Issue by EmDee** [pace/connectedfueling-app-android#1]
### Problem

Changing the fuel type in the sidebar doesn't reload the list reliably; it works very rarely though.

https://user-images.githubusercontent.com/717205/133036158-ea0bcae4-b450-40ff-9f37-b55d56d7f9ca.mp4

**Comment by trmi1012** [comment]
Tested it, seems to not occur anymore. 
List refreshes on fuel type change, therefore closing this.
